// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearProcessMiner.png
var resourceKrankyBearProcessMinerPngData []byte
var resourceKrankyBearProcessMinerPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearProcessMiner.png",
	StaticContent: resourceKrankyBearProcessMinerPngData,
}

//go:embed assets/images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}
