[Details]
ID = "com.github.amarillier.KrankyBearProcessMiner"
Name = "KrankyBear ProcessMiner"
Creator = "Allan Marillier"
  Version = "0.5.0"
Build = 2
Icon = "KrankyBearProcessMiner.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"